---
image: maven:latest
variables:
  SOURCE: "target"

stages:
   - build
   - deploy
   - build_docker_image
  
build-classes-jacoco-job:
   stage: build
   script:
     - $env:Path 
     - $env:M2
     - $env:M2_HOME
     - $env:JAVA_HOME
     - echo $SOURCE
     - mvn clean test
   tags:
      - ci
      - ssh  
deploy-to-server-job:
    stage: deploy
    script:
      - copy-item -path $SOURCE/jacoco.exec -destination d:\\Mahendra
    tags:
      - ci
      - ssh
            
docker_image-job:
    stage: build_docker_image
    script: - docker --version  
    tags:
      - ci
      - ssh 