---
image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
stages:
   - build
  
build-classes-jacoco:
   stage: build
   script:
     - $env:Path 
     - $env:M2
     - $env:M2_HOME
     - mvn $MAVEN_CLI_OPTS compile
   tags:
      - ci
      - ssh  
    