---
image: maven:latest
variables:
  SOURCE: "\target"

stages:
   - build
  
build-classes-jacoco:
   stage: build
   script:
     - $env:Path 
     - $env:M2
     - $env:M2_HOME
     - $env:JAVA_HOME
     #- mvn clean test
     - echo $
     - docker --version
     - copy-item -path $SOURCE/jacoco.exec -destination d:\\Mahendra
   tags:
      - ci
      - ssh  
    