---
image: maven:latest

stages:
   - build
  
build-classes-jacoco:
   stage: build
   script:
     - $env:Path 
     - $env:M2
     - $env:M2_HOME
     - $env:JAVA_HOME
     - mvn clean test
     - docker --version
     
   tags:
      - ci
      - ssh  
    